### PR TITLE
bump dev-nginx to 1.5.0

### PR DESCRIPTION
**Pull request by joelochlann**
As per https://github.com/guardian/dev-nginx/releases/tag/v1.5.0

see also guardian/dev-nginx#28

### CODE REVIEW

**Comment by joelochlann** [comment]
I'm not sure what's up with the build. It seems to be choking on some git conflict lines but I can't see any in the code...

**Comment by akash1810** [comment]
> I'm not sure what's up with the build. It seems to be choking on some git conflict lines but I can't see any in the code...

@shtukas and @jonathonherbert have been looking at this as part of #84. Worth sharing notes?

**Comment by shtukas** [comment]
Ah.... Interesting. Yes we ( @jonathonherbert  and myself ) had a problem with ( https://github.com/guardian/homebrew-devtools/pull/84 , but the successful test at ( https://github.com/guardian/homebrew-devtools/pull/87 ), shows that it's not on every branch 🤔

@joelochlann @akash1810

**Comment by shtukas** [comment]
The only idea I have right now, and that might just be stupid, but I would make a PR from a freshly cloned repository. Might be worth a try.

@joelochlann @jonathonherbert @akash1810

**Comment by akash1810** [comment]
In January, `macos-latest` was moved to macos-12 https://github.com/actions/runner-images/pull/6901. This uses homebrew 4.0.6 https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#package-management.

Looking at https://github.com/guardian/homebrew-devtools/blob/02dd55250ec66d58337ac276f718186ac0c8a059/.github/workflows/ci.yaml#L11, it looks like CI was added to this repository using macos-10.15, which comes with homebtew 3.6.6 https://github.com/actions/runner-images/blob/main/images/macos/macos-10.15-Readme.md#package-management.

That is, we're using a new major version of homebrew.

Maybe worth pinning our CI to `macos-10.15`, and creating an issue to move to `macos-latest` at a later time?

**Comment by joelochlann** [comment]
[Setting `macos-10.15`](https://github.com/guardian/homebrew-devtools/pull/88/commits/0da6e2d72a155a4802c6dd09262f749ac997fa03) didn't work, nor did trying a [fresh clone of the repo](https://github.com/guardian/homebrew-devtools/pull/91)

**Comment by shtukas** [comment]
There is a difference between your attempt and mine. I have an extra line, which seems to make a difference: https://github.com/guardian/homebrew-devtools/pull/90/files#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddR19

**Comment by akash1810** [comment]
https://github.com/guardian/homebrew-devtools/pull/93 offers a fix - the exact cause remains somewhat unknown, but at least the build passes.

**Comment by akash1810** [comment]
#94 has been merged now. A rebase of `main` should get the build in this PR passing 🤞🏽.

**Comment by joelochlann** [comment]
Thanks @akash1810!

**Comment by joelochlann** [comment]
Build looks good! ✅

Are you able to give a 👍 @akash1810?

**Review by akash1810 — APPROVED** [review]

**Pull request merged**
